{{- if (eq .Values.installationMode "OEA-AP") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oes
    component: vela
{{ include "oes.standard-labels" . | indent 4 }}
  name: vela
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: oes
      component: vela
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: oes
        component: vela
{{ include "oes.standard-labels" . | indent 8 }}
      annotations:
        checksum/secret: {{ (.Files.Glob "config/vela/vela-api.yaml").AsConfig | sha256sum }}
{{- if .Values.vela.annotations -}}
        {{ toYaml .Values.vela.annotations | nindent 8 }}
{{- end }}
    spec:
      initContainers:
      - name: db-check
        image: {{ .Values.global.customImages.registry }}/pgchecker:v1
        command:
          - sh
          - -c
          - |
            echo 'Waiting for OES-DB to become ready...'
            until printf "." && nc -z -w 2 oes-db 5432; do
               sleep 2;
            done;
            echo 'OESDB OK ✓'
            sed -e "s@PGPASSWORD@$OPSMX_POSTGRESQL_PASS@g" /opsmx/conf/gate.yml > /tmp/conf/gate.yml
            sed -i "s@REDISPASSWORD@$OPSMX_REDIS_PASS@g" /tmp/conf/gate.yml
            echo success        
        env:
        - name: OPSMX_POSTGRESQL_PASS
          valueFrom:
            secretKeyRef:
              key: pgpassword
              name: oes-db
        - name: OPSMX_REDIS_PASS
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: oes-redis
        volumeMounts:
        - mountPath: /opsmx/conf/
          name: config-volume
        - mountPath: /tmp/conf/
          name: empty-dir-volume
      volumes:
      - name: vela-volume
        configMap:
          name: vela-config
          items:
            - key: vela-api.yaml
              path: vela-api.yaml
          defaultMode: 420
      - name: config-volume
        ConfigMap:
          name: oes-gate-config
          defaultMode: 420
      - name: empty-dir-volume
        emptyDir:
          sizeLimit: 500Mi
      containers:
      - image: {{ template "vela.image" . }}
        imagePullPolicy: IfNotPresent
        name: vela
        ports:
        - containerPort: 8092
          protocol: TCP
        volumeMounts:
          - name: vela-volume
            mountPath: /app/config/vela-api.yaml
            subPath: vela-api.yaml
          - name: empty-dir-volume
            mountPath: /opt/spinnaker/config/gate.yml
            subPath: gate.yml
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      {{- end }}
      terminationGracePeriodSeconds: 30
{{- end -}}
