{{- if (eq .Values.installationMode "OEA-AP") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: oes
    component: gate
{{ include "oes.standard-labels" . | indent 4 }}
  name: oes-gate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oes
      component: gate
  template:
    metadata:
      annotations:
        checksum/secret: {{ (.Files.Glob "config/oes-gate/gate.yml").AsConfig | sha256sum }}
{{- if .Values.gate.annotations -}}
        {{ toYaml .Values.gate.annotations | nindent 8 }}
{{- end }}
      labels:
        app: oes
        component: gate
{{ include "oes.standard-labels" . | indent 8 }}
    spec:
      initContainers:
      {{- if .Values.global.autoConfiguration.enabled }}
      - env:
        - name: EXTERNAL_IP_CHECK_DELAY
          value: "{{ .Values.global.autoConfiguration.initContainer.externalIpCheckDelay}}"
        image: {{ .Values.global.autoConfiguration.initContainer.image}}
        imagePullPolicy: {{ .Values.global.autoConfiguration.initContainer.pullPolicy}}
        name: gate-autoconfig
        command: ["/home/config_endpoint.sh"]
        args: ["oes-gate"]
      {{- end }}
      - name: db-check
        image: {{ .Values.global.customImages.registry }}/pgchecker:v1
        command:
          - sh
          - -c
          - |
            echo 'Waiting for OES-DB to become ready...'
            until printf "." && nc -z -w 2 oes-db 5432; do
               sleep 2;
            done;
            echo 'OESDB OK ✓'
            RABBITMQ_DEFAULT_PASS=`echo $RABBITMQ_DEFAULT_PASS | sed 's/ *$//g'`
            OPSMX_REDIS_PASS=`echo $OPSMX_REDIS_PASS | sed 's/ *$//g'`
            sed -e s/RABBITMQ_DEFAULT_PASS/${RABBITMQ_DEFAULT_PASS}/g /tmp/gate.yml > /tmp/config/gate.yml
            sed -i s/OPSMX_REDIS_PASS/${OPSMX_REDIS_PASS}/g /tmp/config/gate.yml
            {{- if .Values.global.ldap.enabled }}
            LDAP_MANAGER_PASSWORD=`echo $LDAP_MANAGER_PASSWORD | sed 's/ *$//g'`
            sed -i s/LDAP_MANAGER_PASSWORD/${LDAP_MANAGER_PASSWORD}/g /tmp/config/gate.yml
            {{- end }} 
            echo success        
        env:
        - name: OPSMX_POSTGRESQL_PASS
          valueFrom:
            secretKeyRef:
              key: pgpassword
              name: oes-db
        - name: OPSMX_REDIS_PASS
          valueFrom:
            secretKeyRef:
              key: redispassword
              name: oes-redis
        - name: LDAP_MANAGER_PASSWORD
          valueFrom:
            secretKeyRef:
              key: LDAP_ADMIN_PASSWORD
              name: oes-ldap
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              key: rabbitmqpassword
              name: rabbitmq   
        volumeMounts:
        - mountPath: /tmp
          name: gate-config-volume
        - mountPath: /tmp/config
          name: gate-config
      containers:
      - image: {{ template "gate.image" . }}
        name: oes-gate
        env:
        - name: spring_profiles_active
          value: vault,local
       {{- if .Values.extraEnvVars }}
       {{- include "tplvalues.render" (dict "value" .Values.extraEnvVars "context" $) | nindent 8 }}
       {{- end }}
        ports:
        - containerPort: 8084
          protocol: TCP
        resources:
{{ toYaml .Values.gate.resources | indent 12 }}
        volumeMounts:
        - mountPath: /opt/spinnaker/config/gate.yml
          name: gate-config
          subPath: gate.yml
        - mountPath: /opt/spinnaker/config/bootstrap.yml
          name: bootstrap-volume
          subPath: bootstrap.yml
        - mountPath: /opt/spinnaker/config/feature.yml
          name: isd-feature-flag-conf
          subPath: feature.yml
        {{- if .Values.gate.config.saml.enabled }}
        - mountPath: {{ .Values.gate.config.saml.keyStore }}
          name: saml-jks
          subPath: oessaml.jks
        - mountPath: {{ .Values.gate.config.saml.metadataUrl }}
          name: metadata-xml
          subPath: oesmetadata.xml
        {{- end }}
        {{- if .Values.global.customCerts.enabled }}
        - mountPath: /etc/pki/ca-trust/extracted/java/cacerts
          subPath: cacerts
          name: cacerts
        {{- end }}
        readinessProbe:
          tcpSocket:
            port: 8084
          initialDelaySeconds: 60
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /health
            port: 8084
          initialDelaySeconds: 60
          periodSeconds: 60
      {{- if .Values.imagePullSecret}}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret}}
      {{- end }}
      {{- if and (.Values.global.openshift) (not .Values.global.securityContext) }}
      securityContext: {{ default "{}" }}
      {{- else }}
      {{- if and (.Values.global.openshift) (.Values.global.securityContext) }}
      securityContext:
{{ toYaml .Values.global.securityContext | indent 8 }}
      {{- else }}
      {{- if and (not .Values.global.openshift) (.Values.global.securityContext) }}
      securityContext:
{{ toYaml .Values.global.securityContext | indent 8 }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- if .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.global.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.global.affinity }}
      affinity:
{{ toYaml .Values.global.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.global.tolerations }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.gate.config.saml.enabled }}
      - secret:
          secretName: {{ .Values.gate.config.saml.jksSecretName }}
        name: saml-jks
      - secret:
          secretName: {{ .Values.gate.config.saml.metadataSecretName }}
        name: metadata-xml
      {{- end }}
      {{- if .Values.global.customCerts.enabled }}
      - name: cacerts
        secret:
          secretName: {{ .Values.global.customCerts.secretName }}
          items:
          - key: cacerts
            path: cacerts
      {{- end }}
      - configMap:
          defaultMode: 420
          items:
          - key: feature.yml
            path: feature.yml
          name: isd-feature-flag-config
        name: isd-feature-flag-conf
      {{- if .Values.global.autoConfiguration.enabled }}
      - configMap:
          name: oes-gate-config
        name: config-temp
      - emptyDir: {}
        name: gate-config-volume
      {{- else }}
      - configMap:
          name: oes-gate-config
        name: gate-config-volume
      {{- end }}
      - emptyDir: {}
        name: gate-config
      - secret:
          items:
          - key: bootstrap.yml
            path: bootstrap.yml
          secretName: bootstrap
        name: bootstrap-volume
{{- end -}}
