{{- if (eq .Values.installationMode "OEA-AP") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: oes
    component: platform
{{ include "oes.standard-labels" . | indent 4 }}
  name: oes-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oes
      component: platform
  strategy: {}
  template:
    metadata:
      annotations:
        checksum/secret: {{ (.Files.Glob "config/oes-platform/platform-local.yml").AsConfig | sha256sum }}
{{- if .Values.platform.annotations -}}
        {{ toYaml .Values.platform.annotations | nindent 8 }}
{{- end }}
      labels:
        app: oes
        component: platform
{{ include "oes.standard-labels" . | indent 8 }}
    spec:
      {{- if .Values.db.enabled  }}
      initContainers:
      - name: db-check
        image: {{ .Values.global.customImages.registry }}/pgchecker:v1
        command:
          - sh
          - -c
          - |
            echo 'Waiting for OES-DB to become ready...'
            until printf "." && nc -z -w 2 oes-db 5432; do
               sleep 2;
            done;
            echo 'OESDB OK ✓'
            sed -e "s@OPSMX_POSTGRESQL_PASS@$OPSMX_POSTGRESQL_PASS@g" /opsmx/conf/platform-local.yml > /tmp/conf/platform-local.yml
            sed -i "s@OPSMX_REDIS_PASS@$OPSMX_REDIS_PASS@g" /tmp/conf/platform-local.yml
            {{- if .Values.global.ldap.enabled }}
            sed -i "s@LDAP_MANAGER_PASSWORD@$LDAP_MANAGER_PASSWORD@g" /tmp/conf/platform-local.yml
              {{- end }}
            echo success     
        env:
        - name: OPSMX_POSTGRESQL_PASS
          valueFrom:
            secretKeyRef:
              key: OPSMX_POSTGRESQL_PASS
              name: opsmx_postgresql_pass
        - name: OPSMX_REDIS_PASS
          valueFrom:
            secretKeyRef:
              key: OPSMX_REDIS_PASS
              name: opsmx_redis_pass
        {{- if .Values.global.ldap.enabled }}
        - name: LDAP_MANAGER_PASSWORD
          valueFrom:
            secretKeyRef:
              key: LDAP_MANAGER_PASSWORD
              name: ldap_manager_password
        {{- end }}

        volumeMounts:
        - mountPath: /opsmx/conf/
          name: config-volume
        - mountPath: /tmp/conf/
          name: empty-dir-volume
      {{- end }}
      containers:
      - image: {{ template "platform.image" . }}
        name: oes-platform
        env:
       {{- if .Values.extraEnvVars }}
       {{- include "tplvalues.render" (dict "value" .Values.extraEnvVars "context" $) | nindent 8 }}
       {{- end }}
        ports:
        - containerPort: 8095
          protocol: TCP
        resources:
{{ toYaml .Values.platform.resources | indent 12 }}
        readinessProbe:
          tcpSocket:
            port: 8095
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /mgmt/health
            port: 8095
          initialDelaySeconds: 60
          periodSeconds: 60
        volumeMounts:
        - mountPath: /opsmx/conf/platform-local.yml
          name: empty-dir-volume
          subPath: platform-local.yml
        - mountPath: /opsmx/conf/bootstrap.yml
          name: bootstrap-config-volume
          subPath: bootstrap.yml
        - mountPath: /opsmx/conf/standard-error-code.csv
          name: standard-error-conf
          subPath: standard-error-codes.csv
        {{- if .Values.global.customCerts.enabled }}
        - mountPath: /etc/pki/ca-trust/extracted/java/cacerts
          subPath: cacerts
          name: cacerts
        {{- end }}
      {{- if .Values.imagePullSecret}}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret}}
      {{- end }}
      {{- if and (.Values.global.openshift) (not .Values.global.securityContext) }}
      securityContext: {{ default "{}" }}
      {{- else }}
      {{- if and (.Values.global.openshift) (.Values.global.securityContext) }}
      securityContext:
{{ toYaml .Values.global.securityContext | indent 8 }}
      {{- else }}
      {{- if and (not .Values.global.openshift) (.Values.global.securityContext) }}
      securityContext:
{{ toYaml .Values.global.securityContext | indent 8 }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- if .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.global.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.global.affinity }}
      affinity:
{{ toYaml .Values.global.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.global.tolerations }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.global.customCerts.enabled }}
      - name: cacerts
        secret:
          secretName: {{ .Values.global.customCerts.secretName }}
          items:
          - key: cacerts
            path: cacerts
      {{- end }}
      - name: config-volume
        ConfigMap:
          name: oes-platform-config
      - secret:
          items:
          - key: bootstrap.yml
            path: bootstrap.yml
          secretName: bootstrap
        name: bootstrap-config-volume
      - configMap:
          defaultMode: 420
          items:
          - key: standard-error-codes.csv
            path: standard-error-codes.csv
          name: standard-error-codes-config
        name: standard-error-conf
      - name: empty-dir-volume
        emptyDir:
          sizeLimit: 500Mi
{{- end -}}
